cek = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
enft = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkleRoot = ""
nft = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
pubKeys = ["", "", "", ""]
